<?php

namespace App\Filament\Resources;

use App\Enums\ReportTypeEnum;
use App\Filament\Resources\ReportResource\Pages;
use App\Models\Report;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class ReportResource extends Resource
{
    protected static ?string $model = Report::class;

    protected static ?string $navigationIcon = 'heroicon-o-document-chart-bar';

    protected static ?string $navigationGroup = 'System';

    protected static ?int $navigationSort = 3;

    protected static ?string $recordTitleAttribute = 'name';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Report Information')
                    ->schema([
                        Forms\Components\TextInput::make('name')
                            ->required()
                            ->maxLength(255)
                            ->columnSpan(2),
                        
                        Forms\Components\Select::make('type')
                            ->options(ReportTypeEnum::class)
                            ->required()
                            ->live()
                            ->helperText('Select the type of report to generate')
                            ->columnSpan(1),
                        
                        Forms\Components\Select::make('generated_by')
                            ->relationship('generator', 'name')
                            ->required()
                            ->default(auth()->id())
                            ->disabled()
                            ->dehydrated()
                            ->columnSpan(1),
                        
                        Forms\Components\Textarea::make('description')
                            ->rows(3)
                            ->maxLength(500)
                            ->columnSpan(2),
                    ])
                    ->columns(2),

                Forms\Components\Section::make('Report Parameters')
                    ->schema([
                        Forms\Components\KeyValue::make('parameters')
                            ->keyLabel('Parameter Name')
                            ->valueLabel('Value')
                            ->helperText('Add parameters for report generation (e.g., date ranges, filters)')
                            ->addActionLabel('Add Parameter')
                            ->reorderable()
                            ->columnSpan(2),
                    ])
                    ->collapsed(),

                Forms\Components\Section::make('Report Output')
                    ->schema([
                        Forms\Components\TextInput::make('file_path')
                            ->label('File Path')
                            ->helperText('Path where generated report is stored')
                            ->disabled()
                            ->dehydrated(false)
                            ->columnSpan(1)
                            ->visibleOn('edit'),
                        
                        Forms\Components\DateTimePicker::make('generated_at')
                            ->label('Generated At')
                            ->disabled()
                            ->dehydrated(false)
                            ->columnSpan(1)
                            ->visibleOn('edit'),
                    ])
                    ->columns(2)
                    ->visibleOn('edit')
                    ->collapsed(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable()
                    ->sortable()
                    ->weight('bold'),
                
                Tables\Columns\TextColumn::make('type')
                    ->badge()
                    ->formatStateUsing(fn ($state) => $state->label())
                    ->color(fn ($state) => match ($state) {
                        ReportTypeEnum::PROFIT => 'success',
                        ReportTypeEnum::SALES => 'info',
                        ReportTypeEnum::INVENTORY => 'warning',
                        ReportTypeEnum::TAX => 'danger',
                        ReportTypeEnum::CLIENT => 'primary',
                        ReportTypeEnum::PRODUCT => 'gray',
                        default => 'gray',
                    })
                    ->sortable(),
                
                Tables\Columns\TextColumn::make('generator.name')
                    ->label('Generated By')
                    ->sortable()
                    ->searchable()
                    ->toggleable(),
                
                Tables\Columns\TextColumn::make('generated_at')
                    ->label('Generated')
                    ->dateTime()
                    ->sortable()
                    ->since(),
                
                Tables\Columns\IconColumn::make('file_path')
                    ->label('File')
                    ->boolean()
                    ->trueIcon('heroicon-o-document-arrow-down')
                    ->falseIcon('heroicon-o-x-circle')
                    ->trueColor('success')
                    ->falseColor('gray')
                    ->getStateUsing(fn (Report $record) => !empty($record->file_path)),
                
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('type')
                    ->options(ReportTypeEnum::class)
                    ->multiple(),
                
                Tables\Filters\Filter::make('recent')
                    ->label('Recent (30 days)')
                    ->query(fn (Builder $query): Builder => $query->recent(30))
                    ->toggle(),
                
                Tables\Filters\Filter::make('generated_at')
                    ->form([
                        Forms\Components\DatePicker::make('generated_from')
                            ->label('Generated From'),
                        Forms\Components\DatePicker::make('generated_until')
                            ->label('Generated Until'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['generated_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate('generated_at', '>=', $date),
                            )
                            ->when(
                                $data['generated_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate('generated_at', '<=', $date),
                            );
                    }),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
                Tables\Actions\Action::make('download')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('success')
                    ->url(fn (Report $record): ?string => $record->file_path ? asset('storage/' . $record->file_path) : null)
                    ->openUrlInNewTab()
                    ->visible(fn (Report $record): bool => !empty($record->file_path) && $record->fileExists()),
                Tables\Actions\Action::make('regenerate')
                    ->icon('heroicon-o-arrow-path')
                    ->color('warning')
                    ->requiresConfirmation()
                    ->action(fn () => null)
                    ->visible(fn () => false), // Hide until regeneration service is implemented
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->defaultSort('generated_at', 'desc');
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListReports::route('/'),
            'create' => Pages\CreateReport::route('/create'),
            'edit' => Pages\EditReport::route('/{record}/edit'),
            'view' => Pages\ViewReport::route('/{record}'),
        ];
    }

    public static function getNavigationBadge(): ?string
    {
        $count = static::getModel()::recent(7)->count();
        return $count === 0 ? null : (string) $count;
    }
}
